server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BillingService
    username: postgres
    password: Prati@13

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: BILLING-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka