server:
  port: 8084


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medicineservice
    username: root
    password: Prati@13
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: MEDICINE-SERVICE


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
